# Generated by Django 4.0.3 on 2022-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
