# Generated by Django 4.0.3 on 2022-04-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_channel_title'),
        ('main_app', '0005_rename_profile_userprofile'),
    ]

    operations = [
    ]
