# Generated by Django 4.0.3 on 2022-04-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20220411_1345'),
        ('main_app', '0006_merge_20220411_1348'),
    ]

    operations = [
    ]
