# Generated by Django 4.0.3 on 2022-04-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_channel_user'),
        ('main_app', '0008_thread_channel'),
    ]

    operations = [
    ]
