# Generated by Django 4.0.3 on 2022-04-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0007_channel_user_0007_merge_20220411_1518'),
        ('main_app', '0009_merge_0007_channel_user_0008_thread_channel'),
    ]

    operations = [
    ]
