# Generated by Django 4.0.3 on 2022-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20220412_0801'),
        ('main_app', '0010_merge_20220412_0804'),
    ]

    operations = [
    ]
