# Generated by Django 4.0.3 on 2022-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20220412_0849'),
        ('main_app', '0011_merge_20220412_0851'),
    ]

    operations = [
    ]
