# Generated by Django 4.0.3 on 2022-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20220412_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
