# Generated by Django 4.0.3 on 2022-04-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20220412_1321'),
        ('main_app', '0012_thread_header_image'),
    ]

    operations = [
    ]
