# Generated by Django 4.0.3 on 2022-04-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220413_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='header_image',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
