# Generated by Django 4.0.3 on 2022-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220413_1234'),
        ('main_app', '0014_remove_thread_header_image_delete_photo'),
    ]

    operations = [
    ]
