# Generated by Django 4.0.3 on 2022-04-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_merge_20220413_1338'),
        ('main_app', '0016_comment'),
    ]

    operations = [
    ]
