# Generated by Django 4.0.3 on 2022-04-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220413_1238'),
        ('main_app', '0017_merge_0015_merge_20220413_1338_0016_comment'),
    ]

    operations = [
    ]
