# Generated by Django 4.0.3 on 2022-04-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_comment_user_alter_thread_user'),
        ('main_app', '0019_merge_20220413_1949'),
    ]

    operations = [
    ]
